name: cwmonkey.github.io
title: cwmonkey.github.io
description: my site
author:
  name: cwmonkey
  email: monkey@mysmilies.com

domain: cwmonkey.github.io
protocol: https
javascripts: javascripts.html
stylesheets: stylesheets.html
debug: false
