# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: cwmonkey.github.io
description: 
author:
  name: cwmonkey
  email: monkey@mysmilies.com

domain: cwmonkey.github.io
javascripts: javascripts-minify.html
stylesheets: stylesheets-minify.html
# Grunt handles images and assets.
# exclude: ['images', 'css', 'js', 'fonts',
#           '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

# Markdown library
markdown: redcarpet
#   extensions: ['fenced_code_blocks', 'smart']

pygments: true